import type { Metadata } from 'next';
import { Header, Footer } from '@/components';
import ThemeProvider from '@/contexts/ThemeProvider';
import 'react-loading-skeleton/dist/skeleton.css';
import '@/styles/tailwind.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className="antialiased"
      suppressHydrationWarning
    >
      <head>
        <meta name="msapplication-TileColor" content="#000000" />
        <meta
          name="theme-color"
          media="(prefers-color-scheme: light)"
          content="#eee"
        />
        <meta
          name="theme-color"
          media="(prefers-color-scheme: dark)"
          content="#000"
        />
      </head>
      <body
        className="antialiased
          bg-background-main-light text-main-light dark:bg-background-main-dark dark:text-main-dark
        "
      >
        <ThemeProvider>
          <div className="mx-auto max-w-5xl px-4 sm:px-6 xl:px-0">
            <Header />
            <main className="min-h-[calc(100vh-300px)] py-2 sm:pt-6 sm:pb-8">
              {children}
            </main>
          </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
